### ISSUE TITLE
Worldboss ping problem

### ISSUE THREAD

**Issue by Tilphia** [sguo1123/SMMOBot-Teddybear#1]
The first worldboss of the week doesn't get pinged. The WB timer only appears after the first WB is attackable and shows the next one completely ignoring the first WB.

**Comment by HugTeddy** [comment]
Looks like this occurs due to the lowered API calls when bosses are done each week. I have increased the update frequency, so it should catch the first boss each week. I will test it over the next few weeks to see if another solution is necessary.

**Comment by HugTeddy** [comment]
Should be resolved now.
