### ISSUE TITLE
Guild Safe Check should be sorted based on levels

### ISSUE THREAD

**Issue by crazy-vedic** [sguo1123/SMMOBot-Teddybear#10]
Guild safecheck list should be sorted based on levels, and, if possible, both the level and weekly pvp kills should be visible next to the users name, maybe in brackets before their name

**Comment by crazy-vedic** [comment]
also number of users out of safe should be in footnote

**Comment by HugTeddy** [comment]
Added footnote with total players and level sorting, will not be adding weekly kills at this point
