### ISSUE TITLE
Tipping Resets Without Giving Tip

### ISSUE THREAD

**Issue by Jurg55** [sguo1123/SMMOBot-Teddybear#12]
If you don't use the tip command like 100% correctly it won't tip the user (gives red x reaction y'know) but it still resets your cooldown. For example, if instead of @ ing the user you just type their username, or if you do the @ and it just..  doesn't @, the tip won't go through but it resets your cooldown. I also believe it does this if you simply put `~tip` but it's been awhile since I last did that so I can't be 100% sure.

**Comment by HugTeddy** [comment]
Updated, should only add cooldown if initial parameters are met

**Comment by HugTeddy** [comment]
Should be resolved now, only once parameters are met and tip is given will the command go on cooldown
