### ISSUE TITLE
Update for guild war functionality

### ISSUE THREAD

**Issue by crazy-vedic** [sguo1123/SMMOBot-Teddybear#13]

**Comment by crazy-vedic** [comment]
For every active guild/guild that has called warlist at least once, the bot should automatically update the values every 24 hours. When this is done, the daily/or more than daily values depending on if the members manually call it should be made into a time/kills graph, with 2 line graphs displaying each guilds kills over time. An example is here: https://media.discordapp.net/attachments/786948013888634920/857254681479086151/line-graph_66.png?width=518&height=337  to get a graph, command ~war (guild ID) should be called; own gnild should be in blue and enemy in red.

**Comment by HugTeddy** [comment]
Ill take a look at it, would have loved it if all the wars were sorted so that the guild you're looking up showed up on the same side.

**Comment by HugTeddy** [comment]
Updated with new endpoints, wars are now sorted on one side and listed in order of completion.
