### ISSUE TITLE
Add ability to see individual stats in the last week

### ISSUE THREAD

**Issue by dlsnyder8** [sguo1123/SMMOBot-Teddybear#14]
**Explanation**
Currently to only options to see stats for the last week are to either run 7 commands (one for each day) to get your stats for the last week OR you can run the `~graph` command, but this does not tell you exactly how many steps/kills/quests you did per day.

**Request**
Make a new command called `detailedstats` that returns the last 7 (full) days worth of stats as an embed.
You could also change the `graph` command to show the values of the bars, but since it's such a small space this might not be ideal.

**Comment by HugTeddy** [comment]
Added feature `~detailedstats`
