### ISSUE TITLE
Add hyperlinks to usernames in leaderboards

### ISSUE THREAD

**Issue by dlsnyder8** [sguo1123/SMMOBot-Teddybear#15]
**Feature Request:**

On all guild leaderboards (daily activity, advanced leaderboard, and guild leaderboard commands), add hyperlinks to user's profiles. This would aid in finding their profile in game more easily.

![image](https://user-images.githubusercontent.com/51924672/126211401-45c3bdb7-916a-4ff3-b75f-1abb9d7aaa40.png)

**Comment by HugTeddy** [comment]
Updated Guild Leaderboards, Daily Leaderboards, and Top10
