### ISSUE TITLE
Suggestion: you are leaving safe mode in {amount of time} not 'soon'

### ISSUE THREAD

**Issue by crazy-vedic** [sguo1123/SMMOBot-Teddybear#17]
![image](https://user-images.githubusercontent.com/66624689/133891280-ad8fd6f9-203d-4d27-b428-098e8e3a0734.png)
you are leaving safe mode in {amount of time} not 'soon'

**Comment by HugTeddy** [comment]
Generally, this message is sent a few min before leaving safe mode. Duration is not long enough to warrant an additional countdown.
