### ISSUE TITLE
Guild Leaderboard EXP

### ISSUE THREAD

**Issue by dlsnyder8** [sguo1123/SMMOBot-Teddybear#2]
The guild leaderboard EXP doesn't update w/ the V9 experience amounts. It's been sitting at the pre-V9 experience.

**Comment by HugTeddy** [comment]
Thanks for letting me know. Unfortunately, the API calls for guild data seem to be set to the pre v9 values, I have hotfixed this with web scraping for the top 10-15 guilds, however, due to the impending change to the web app, a permanent fix will likely be delayed until that update. Will look into

**Comment by HugTeddy** [comment]
Guild Exp is now hidden to non-guild members, therefore these stats will not be public unless added with public API update
