### ISSUE TITLE
Weekly quest function: Allow custom timeframe

### ISSUE THREAD

**Issue by Cryysys** [sguo1123/SMMOBot-Teddybear#21]
Thanks for adding the weekly quest function Ted! Right now we got the option to get the information from exactly one week in the past with TedBot, it'd be awesome if we could customize that timeframe a bit. Right now if we miss the timeframe of exactly one week after the weekly quests start, we might not count a few hours of time.

**Comment by HugTeddy** [comment]
Added, new command is `~quests startdate enddate type amount` e.g. `~quests 2021/11/1 2021/11/6 quests 100`
