### ISSUE TITLE
Put Emote Corresponding to Award for "Misc Stats" on "~p+" Page

### ISSUE THREAD

**Issue by HoDzNochan** [sguo1123/SMMOBot-Teddybear#23]
Currently, when you pull up the "~p+" page, the "Misc Stats" section doesn't have any emotes.
However, of the "Misc Stats", Tasks Completed, World Bosses Killed, Bounties Completed, and Chests Opened have awards associated with them.
My suggestion is to have the bot put an emote of each stat's corresponding award tier to make people's profiles on the bot look more colorful and complete.
For example, if a user has opened 4,321 chests, there would be an emote of the "Vault Hunter" award next to the count, because they've opened the 1,000 chests required to get the award, but not the 10,000 required to get the award of the next tier up, "Captain Chest".
Another example is if a user has completed 300 bounties, there would be an emote of the "Death Delivered First Class" award icon next to their count, as that is the highest tier of the bounty hunter award they've unlocked.

**Comment by HugTeddy** [comment]
Updated V1 
![image](https://user-images.githubusercontent.com/62405530/147416007-0ad72db1-6919-4776-99fc-42f56a57b092.png)

Might add similar change to Steps/Kills

**Comment by HugTeddy** [comment]
Added to both stat sections
![image](https://user-images.githubusercontent.com/62405530/147422290-660bba16-c865-44a6-a3f5-89bc2d00d2a3.png)
