### ISSUE TITLE
War Notifications

### ISSUE THREAD

**Issue by TheRealBigSwift** [sguo1123/SMMOBot-Teddybear#26]
It would be a pretty neat idea if the bot could in some way keep track of wars and ping a certain role on the discord when you get put in a losing position and/or when another guild gets within 100 kills of you.

**Comment by HugTeddy** [comment]
That might be an interesting addition

**Comment by HugTeddy** [comment]
BETA ready for testings `~warsetup roleid` should setup the channel correctly to get notifications

**Comment by HugTeddy** [comment]
Updated with hold notifications, when another guild has surpassed your kill count, and role pings

**Comment by HugTeddy** [comment]
Added check for war completion

**Comment by HugTeddy** [comment]
Commands/Feature in Place
