### ISSUE TITLE
~dc circuit voltage

### ISSUE THREAD

**Issue by MistakenPossum686** [sguo1123/SMMOBot-Teddybear#29]
Hello.

I believe one of the ~dc quiz game questions offered in SMMO's Gorilla Wizards guild Discord (and other places, I assume) may have a wrong answer. It does not accept that the voltage applied to the circuit is 18V. Here's why I believe that is the correct answer.

The question has two resistors in parallel, R1 and R2, and resistor R3 in series. The current through the circuit is 3A. R3 has a resistance of 2 ohms, and R1 and R2 have resistances of 6 and 12 ohms. To maintain a consistent voltage across the parallel resistors, the currents through them are inversely proportional to their resistance, so the 12-ohm resistor has 1A of current, and the 6-ohm resistor has 2A of current. In both cases, since V=IR, the voltage across each of the parallel resistors is 12V, and the voltage across R3 is 6V. So, the voltage applied to the circuit is 18V, the sum of the two.

**Comment by HugTeddy** [comment]
You are correct, the question should now have the correct answer applied. A rune has been credited to your account.
