### ISSUE TITLE
Quest Amount Wrong

### ISSUE THREAD

**Issue by EclipseTheWitch** [sguo1123/SMMOBot-Teddybear#3]
Heyo, i noticed today that the ~p shows that i have completed 129k quest yet my in game stats are 4k less than that.

**Comment by HugTeddy** [comment]
Looks like the public API and the given data do not match, hopefully, this is resolved with the new web app update. Otherwise I will correct by scraping web app or sticking to API calls

**Comment by HugTeddy** [comment]
API has not been updated new counter includes all quests performed
