### ISSUE TITLE
Suggestion: HP to 50% Timer

### ISSUE THREAD

**Issue by TheRealBigSwift** [sguo1123/SMMOBot-Teddybear#30]
Command: ~hp User ID
Action: does the maths to spit out how long left until a certain player until they tick to 50% hp and are attackable
Preview: *user submits command* output - [610] BigSwift has 10 minutes and 25 seconds until 50% hp

**Comment by HugTeddy** [comment]
Added in part to `~guildTargetCheck` and profile embeds
