### ISSUE TITLE
Suggestion/Request

### ISSUE THREAD

**Issue by TheRealBigSwift** [sguo1123/SMMOBot-Teddybear#31]
Would it be possible to split the wars won notification and be able to have that post to a specific channel separately from the on hold/losing/tied notifications?

**Comment by HugTeddy** [comment]
Should be added now as beta, command is `~warnoti <group>` where groups could be `main`, `hold`, and `loss`

**Comment by HugTeddy** [comment]
Added `~warnoti <group>` to commands, groups include `main`, `hold`, `loss`, and `wins`
