### ISSUE TITLE
~userinfo isnt working for me

### ISSUE THREAD

**Issue by Fjordrabe** [sguo1123/SMMOBot-Teddybear#34]
SimpleMMO ID/Username: Raven, Artistic Way Cultivator (663531)
Type Of Issue: [Bug Report]
Issue:

The command ~userinfo isn't working for me. 
The error: An error occurred, if persistent please check out our Discord Support Server ^aboutme.

**Comment by HugTeddy** [comment]
This should be working now, it will take up to 36 hours for stats the register. It will also take up to 30 days to register averages.
