### ISSUE TITLE
Suggestion: Worldboss Link sent

### ISSUE THREAD

**Issue by crazy-vedic** [sguo1123/SMMOBot-Teddybear#4]
When a worldboss timer goes to 0, the final ping should be accompanied with a link to the worldboss like: https://web.simple-mmo.com/worldboss/attack/430?new_page=true

**Comment by HugTeddy** [comment]
Added a link on the last message, will update to a specific link next cycle.

**Comment by HugTeddy** [comment]
Added in the update. Will send links in the last message.
